/* Intuition builders — Track 2 (advanced). One per module, 4 levels each. */

COURSE.registerExplainer({
  id: 'x-m14', moduleId: 'm14-fine-tuning', title: 'Fine-tuning in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The base model is a <b>brilliant generalist new hire</b>. Prompting is leaving sticky notes on their monitor each morning; RAG is giving them a searchable filing cabinet; fine-tuning is <b>sending them on a training course that rewires their instincts</b>. Courses are expensive, slow, and stick permanently — so you don\'t send someone on a course to memorize this week\'s prices (that\'s the filing cabinet\'s job). You send them to internalize a <em>skill or style</em> they\'ll apply thousands of times: your house tone, a niche output format, a domain\'s reasoning patterns. Do it for the wrong reason and you\'ve paid a fortune to teach facts that were stale by Tuesday.</p>' },
    { name: '🔬 Technical', html: '<p>Fine-tuning continues training on curated data to shift behavior. <b>SFT</b> minimizes next-token loss on (prompt→ideal-response) pairs with the loss masked to the response. <b>LoRA/QLoRA</b> freeze the base weights and learn small low-rank adapter matrices (ΔW = BA, rank 8–64) — 0.1–1% of params, so an 8B tunes on one 24GB GPU and 70B fits ~48GB with 4-bit QLoRA. <b>Preference tuning</b> (DPO, and RLHF) then optimizes chosen-over-rejected pairs to shape tone and refusals. The decision order that saves money: prompt → few-shot → RAG → <em>then</em> fine-tune, and never fine-tune to inject knowledge.</p>' },
    { name: '⚙️ Internals', html: '<p>LoRA works because task adaptation lives in a low-rank subspace of weight-space; you learn B and A such that the effective update BA nudges attention/MLP projections without disturbing the pretrained manifold. QLoRA quantizes the frozen base to 4-bit (NF4) and keeps adapters in bf16 — the base is read-only so quantization error doesn\'t compound. DPO reparameterizes the RLHF objective so the optimal policy has a closed form relative to a frozen reference model, with a KL leash preventing drift — no reward model, no rollout loop. Data quality dominates: LIMA showed ~1k excellent examples beat 50k mediocre ones; duplicates and contaminated eval data silently wreck results.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Knowledge injection is the classic mistake:</b> facts fine-tune in unreliably, interfere with each other, and go stale — use RAG.</li><li><b>Catastrophic forgetting:</b> narrow fine-tunes degrade general capability; always eval on a held-out general set, not just your task.</li><li><b>The maintenance tail:</b> every base-model upgrade means re-tuning; a prompt would have just carried over.</li><li><b>Wrong chat template = silent quality collapse</b> when serving the tuned model.</li><li><b>Overfitting on small sets:</b> 3+ epochs on 500 examples memorizes; watch eval loss, not train loss.</li><li><b>Preference data is subtle:</b> annotator inconsistency teaches noise; agreement rates matter more than volume.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m15', moduleId: 'm15-inference-internals', title: 'Inference internals in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Serving an LLM is a <b>kitchen</b>. <b>Prefill</b> is reading the entire order ticket at once — fast, done in a glance. <b>Decode</b> is plating one item at a time, walking back to the pantry (HBM) for ingredients on every single plate — that walk, not the chef\'s speed, sets the pace. The <b>KV cache</b> is the mise en place you keep on the counter so you don\'t re-chop for every plate; it grows with the meal until the counter (VRAM) is full. <b>Continuous batching</b> is cooking many tables\' dishes on one stove, swapping a finished dish out for a new one mid-service instead of waiting for the whole batch. <b>Quantization</b> is lighter ingredients so each pantry trip carries less weight.</p>' },
    { name: '🔬 Technical', html: '<p>Prefill is compute-bound (one parallel pass over the prompt, filling the KV cache); decode is memory-bandwidth-bound (one token per pass, re-reading weights + cache from HBM). So tokens/sec ≈ HBM bandwidth ÷ bytes-read-per-token, and input tokens price ~3–5× under output. KV cache bytes = 2 × layers × kv_heads × head_dim × dtype × tokens × batch — at long context it can rival the weights, which is why GQA/MQA shrink kv_heads. <b>Continuous batching</b> (vLLM/PagedAttention) admits and evicts requests per step for 5–20× throughput. <b>Quantization</b> (INT4/INT8/FP8, GGUF/AWQ) and <b>speculative decoding</b> (small draft + parallel verify) cut latency further.</p>' },
    { name: '⚙️ Internals', html: '<p>PagedAttention stores the KV cache in fixed-size pages like OS virtual memory, eliminating the fragmentation that forced pre-reserving contiguous max-length buffers — that\'s what unlocked high batch occupancy. Speculative decoding exploits that verifying k tokens costs one forward pass: the draft proposes, the target verifies in parallel, and the longest prefix matching the target\'s own distribution is accepted (output is provably identical to the target alone). Quantization error concentrates in outlier activation channels — AWQ/SmoothQuant protect those channels, which is why naive round-to-4-bit degrades more than method-aware 4-bit. FP8 on newer hardware gives near-FP16 quality at ~half the bytes.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>TTFT vs tokens/sec are different SLOs</b> with different bottlenecks (prefill vs decode) — optimize the one users feel.</li><li><b>Long context silently OOMs</b> via the KV cache even when weights fit comfortably.</li><li><b>Throughput and latency trade off:</b> bigger batches raise tokens/sec but each request waits longer.</li><li><b>Quantization quality loss is task-dependent</b> — fine on chat, visible on hard reasoning/code; measure, don\'t assume.</li><li><b>Speculative decoding barely helps on high-entropy text</b> (creative writing) where the draft mis-guesses.</li><li><b>Continuous batching is the source of temperature-0 nondeterminism</b> (batch composition changes reduction order).</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m16', moduleId: 'm16-open-models', title: 'Open models in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>API models are <b>ride-share</b>: instant, no garage, you pay per trip and never see the engine. Open models are <b>buying a car</b>: upfront hassle (a GPU, drivers, the right fuel grade) but no per-mile fee, full privacy, and you can mod the engine (fine-tune). The rookie mistake is buying a supercar (70B) to commute two miles to fetch coffee — a compact hatchback (an 8B) does the errand fine, fits your garage (a 24GB card), and costs nothing to idle. And the fuel grade matters absurdly much: put the wrong chat template in and a perfectly good engine sputters, with no warning light.</p>' },
    { name: '🔬 Technical', html: '<p>As of early 2026 the open landscape (Llama, Qwen, DeepSeek, Mistral, Gemma families) delivers frontier-2023 quality at 7–70B, mostly under permissive-ish licenses (read them — "open weights" ≠ OSI open source). <b>llama.cpp</b> runs GGUF-quantized models on CPU/GPU/Metal with partial offload; <b>Ollama</b> is its friendly wrapper. Sizing: pick the smallest model that clears your task\'s quality bar, then quantize to fit VRAM (a Q4_K_M 8B needs ~6GB). Self-hosting economics hinge on utilization: rented GPUs bill by the hour whether busy or idle, so the break-even vs API pricing arrives only at sustained high volume — or when privacy, latency, or custom fine-tunes force your hand.</p>' },
    { name: '⚙️ Internals', html: '<p>GGUF quant levels trade bits for quality: Q4_K_M (4-bit, mixed) is the sweet spot; Q8 is near-lossless and larger; Q2/Q3 degrade visibly. <code>-ngl N</code> offloads N transformer layers to GPU; the rest run on CPU RAM at a bandwidth penalty, so partial offload of a too-big model is often slower than a smaller model fully on GPU. The chat template (special tokens like <code>&lt;|start_header_id|&gt;</code>, the exact system/user/assistant framing) is baked in during SFT; llama.cpp/Ollama ship per-model templates, and a mismatch means the model never sees the format it was trained to complete — output quality collapses with zero errors.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>"Open" is a license spectrum:</b> some forbid commercial use or training competitors — read before shipping.</li><li><b>Utilization is the whole economic argument:</b> a mostly-idle rented H100 is far pricier per request than an API.</li><li><b>Ops burden is real:</b> you now own upgrades, security, capacity, and on-call for the model server.</li><li><b>Quantize-large vs full-small:</b> a Q4 70B and a Q8 32B may cost similar VRAM — benchmark both on YOUR task.</li><li><b>Wrong template = silent collapse</b> — the #1 open-model footgun.</li><li><b>Small-model capability rises quarterly</b> (distillation) — re-test "too weak" verdicts regularly.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m17', moduleId: 'm17-multimodal', title: 'Multimodal in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>A vision-language model doesn\'t "see" a picture — it <b>skims a description of a grid of tiles</b>. The image is chopped into patches, each patch becomes a few tokens, and those tokens join the text stream. So it\'s great at "what\'s the gist / read this sign / summarize this chart" and shaky at "how many red dots exactly" or "what\'s the precise pixel layout" — like someone recapping a photo from memory rather than measuring it. Voice agents add a stopwatch: humans expect a reply within about half a second, so the whole listen→think→speak loop is a latency budget, not just a quality problem.</p>' },
    { name: '🔬 Technical', html: '<p>Images enter as patch/tile tokens from a vision encoder projected into the LLM\'s embedding space; a high-res page can cost hundreds to thousands of tokens (resolution × tiling drives cost). VLMs excel at OCR, captioning, chart/screenshot understanding and document layout, but are weak on precise counting, fine spatial reasoning, and exact geometry. Document pipelines choose between native text extraction, OCR, and vision-model parsing (best for messy layouts/tables, at token cost). Voice stacks are STT → LLM → TTS or newer speech-to-speech/realtime APIs targeting sub-~500ms turn latency with barge-in. Image generation (diffusion, increasingly autoregressive) is a separate model class you call as a tool.</p>' },
    { name: '⚙️ Internals', html: '<p>Most VLMs bolt a pretrained vision encoder (ViT/CLIP-style) onto the LLM via a projection layer, trained on image-text pairs — the LLM learns to attend over visual tokens as if they were words. Tiling schemes (e.g. splitting a high-res image into a grid plus a downsized global view) balance detail against token budget; that budget is why "just send the full-res 4K scan" quietly 10×es your cost. Realtime voice APIs collapse the STT/LLM/TTS pipeline into one model to cut the latency of three network hops and preserve prosody, streaming audio in and out token-by-token. Counting fails because attention over patch tokens has no built-in enumeration mechanism.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Token cost scales with resolution/tiling</b> — high-res images are a silent cost multiplier; downscale to the smallest that preserves the needed detail.</li><li><b>Counting and precise spatial tasks are unreliable</b> — verify with classical CV where accuracy matters.</li><li><b>OCR-via-VLM can hallucinate plausible text</b> in blurry regions rather than erroring.</li><li><b>Voice latency budgets are unforgiving</b> — every component (STT, LLM TTFT, TTS) eats the ~500ms bar.</li><li><b>Native text beats vision parsing when the PDF has a real text layer</b> — don\'t pay vision tokens for extractable text.</li><li><b>Multimodal safety is immature</b> — injection via text-in-images is a live attack surface.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m18', moduleId: 'm18-cost-latency', title: 'Cost & latency in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Sending every query to the frontier model is <b>flying first-class to the corner shop</b>. Most requests are errands a compact model handles for a twentieth of the price — so you put a <b>dispatcher</b> (router) at the door that sends easy trips cheap and escalates only the hard ones. A <b>semantic cache</b> is remembering you already answered a near-identical question five minutes ago and just handing back the receipt. <b>Streaming</b> doesn\'t make the trip faster — it\'s the waiter bringing bread immediately so the table doesn\'t feel the wait. And <b>token dieting</b> is not over-packing every suitcase you send, since you\'re billed by the pound each way.</p>' },
    { name: '🔬 Technical', html: '<p>The big levers: <b>model routing</b> (classify difficulty, send easy → small model, hard → frontier; 5–10× savings on mixed traffic); <b>semantic caching</b> (embed the query, serve a stored answer on a near-match — huge on repetitive traffic, with a correctness risk on loose thresholds); <b>cascades</b> (cheap model + verifier, escalate on failure); <b>token dieting</b> (prompt compression, history caps, trimming tool outputs, capping output length); <b>batch APIs</b> (~50% off for async, non-latency-critical jobs); and <b>streaming UX</b> (TTFT is the felt latency, not total time). Bake per-feature unit economics into dashboards and gate cost regressions in CI.</p>' },
    { name: '⚙️ Internals', html: '<p>Routers range from cheap heuristics (length, keywords) to a small classifier trained on (query → which-model-suffices) labels mined from logs. Semantic caches key on query embeddings with a similarity threshold; the failure mode is a near-miss hit returning a subtly wrong stored answer, so thresholds run conservative and cache entries carry TTLs/invalidation. Cascades rely on a cheap, reliable verifier (schema check, judge, self-consistency) — if verification is as expensive as the frontier call, the cascade loses. Streaming\'s TTFT is dominated by prefill (prompt length) plus queue wait; prompt caching cuts prefill, shortening the number users actually perceive.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Semantic cache near-misses serve wrong answers</b> confidently — tune thresholds and monitor hit correctness.</li><li><b>Routing mistakes cut both ways:</b> under-routing wastes money, over-routing ships a weak answer — measure escalation precision.</li><li><b>Output tokens dominate cost at short prompts</b> — cap length and prune rambling before chasing input savings.</li><li><b>Tool-output bloat compounds in agent loops</b> (re-sent every step) — the highest-ROI diet.</li><li><b>Batch APIs trade latency for ~50%</b> — never use realtime pricing for offline jobs.</li><li><b>Don\'t stream when you must scan output first</b> (moderation/guardrails) — streaming and output-filtering fight.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m19', moduleId: 'm19-production-patterns', title: 'Production patterns in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Treat the LLM like <b>any flaky third-party dependency you don\'t control</b> — because you don\'t. You wouldn\'t let a payment gateway\'s hiccup take down checkout, so <b>AI down ≠ product down</b>: have a second provider and a graceful degraded mode. Shipping a prompt change straight to 100% of users is deploying to prod on a Friday with no tests — instead you <b>canary</b> it to 5%, watch the eval metrics, and auto-roll-back on a dip. And you version the whole bundle — prompt + model + params + tools — as one release, so "reproduce yesterday\'s behavior" is a checkout, not an archaeology dig.</p>' },
    { name: '🔬 Technical', html: '<p>Core patterns: <b>fallbacks</b> (multi-provider failover across different vendors, timeout ladders, circuit breakers, capability-degraded modes); <b>guarded rollouts</b> (shadow traffic, percentage canaries for prompt/model changes, auto-rollback on eval-metric regression); <b>versioning</b> (prompt+model+params+tools as one deployable, config-as-code, pinned model snapshots); <b>abuse prevention</b> (per-user/tenant rate limits and token budgets, jailbreak/spam defenses, free-tier resale detection); and <b>queues vs sync</b> (async jobs with status UX for long agent runs). Multi-tenancy adds noisy-neighbor rate-limit isolation, per-tenant cost attribution, and RAG data isolation.</p>' },
    { name: '⚙️ Internals', html: '<p>A resilience wrapper fronts every call: try primary with jittered exponential backoff on 429/5xx, trip a circuit breaker after repeated failures to stop hammering a dead provider, fail over to a <em>different vendor</em> (a portable prompt abstraction makes this possible), and degrade to cache/canned responses as last resort. Canary rollouts compare the candidate\'s live eval/guardrail metrics against the incumbent on a traffic slice; a threshold breach triggers automatic rollback. Versioning means the prompt, model id, sampling params, and tool schemas are one immutable artifact — because a model snapshot moving under a fixed prompt is a silent behavior change.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Same-vendor failover doesn\'t survive a provider-wide outage</b> — your secondary must be a different vendor.</li><li><b>Silent model updates break prompts</b> — pin snapshots and regression-gate upgrades.</li><li><b>Retries without idempotency double-charge or double-act</b> — key retries on request ids.</li><li><b>Naive stream-retry shows the first half twice</b> — dedupe partial output.</li><li><b>Free-tier abuse (reselling your API via your product) is an economic attack</b>, not just spam — budget per tenant.</li><li><b>Long agent jobs need async + status UX</b> — a 3-minute synchronous request is a timeout waiting to happen.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m20', moduleId: 'm20-system-design', title: 'AI system design in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Designing an AI feature is <b>designing a restaurant, not buying a fancier oven</b>. Newcomers obsess over the model ("get the best oven"); the diners\' experience is decided by the whole flow — how orders are taken (requirements), where ingredients come from and how fresh (data), which dishes go to the line cook vs the head chef (model tier & routing), how you plate under a plate-size limit (context strategy), what happens when a dish comes back (failure modes & guardrails), how you know the food is good (evals), and whether the numbers close (unit economics). A great oven in a broken kitchen still ships bad dinners.</p>' },
    { name: '🔬 Technical', html: '<p>A reusable method turns every AI system-design problem into the same checklist: <b>(1) requirements</b> (task, quality bar, latency/cost SLOs, scale); <b>(2) data & freshness</b> (what grounds it, how current, RAG vs fine-tune vs context); <b>(3) model tier & routing</b> (smallest that clears the bar, escalation); <b>(4) context strategy</b> (budget the window: system/tools/history/RAG/output); <b>(5) failure modes & guardrails</b> (hallucination, injection, blast radius, HITL gates); <b>(6) evals & rollout</b> (golden set, regression gate, canary); <b>(7) unit economics</b> (tokens/request × traffic × price, cache strategy). Support bots, coding assistants, research agents, and doc pipelines are all this method with different weights.</p>' },
    { name: '⚙️ Internals', html: '<p>The method composes every prior module. A support bot = RAG (m6/7) + context budgeting (m8) + guardrails (m13) + evals (m11) + routing (m18) + tracing (m12), with escalation-to-human as the safety valve. A doc pipeline = structured outputs (m5) + batch API (m18) + human QA sampling (m11) + per-doc cost math. The discipline is doing capacity and cost arithmetic <em>up front</em> — tokens/request × requests/day × $/Mtok, with a caching assumption — and naming "where this breaks first" (usually retrieval quality or tail-latency under load) before writing code, so the architecture answers those pressures by design.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Leading with the model is the tell of a junior design</b> — lead with requirements and data.</li><li><b>Skipping the token-budget math</b> is how features ship and then blow the cost model in week one.</li><li><b>No eval plan = no way to know a change helped</b> — design the golden set alongside the system.</li><li><b>Every design breaks somewhere first</b> — if you can\'t name it, you haven\'t finished designing.</li><li><b>Freshness requirements silently pick your architecture</b> (real-time data ⇒ RAG/tools, not fine-tune).</li><li><b>Guardrails and HITL are load-bearing, not garnish</b>, for anything with blast radius.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m21', moduleId: 'm21-frontier', title: 'The frontier in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The frontier is <b>weather vs climate</b>. The daily weather — which model tops which leaderboard, the newest API flag, this month\'s parameter count — churns constantly and you\'ll drive yourself mad chasing it. The climate — token economics, eval discipline, the security model, context as a budget, "measure on your own data" — barely moves and is what actually keeps you employable. Reasoning models are the current headline: models trained to <b>think longer before answering</b>, spending compute at question-time instead of only at training-time. Powerful for genuinely hard problems, wasteful (and slow) for the easy ones — a sports car in a school zone.</p>' },
    { name: '🔬 Technical', html: '<p>As of early 2026 the live frontier themes: <b>test-time compute</b> (reasoning models trained with RL on verifiable rewards spend a private "thinking" token budget — big gains on math/code/planning, at latency and cost premiums); <b>agent swarms / parallelism</b> (best-of-N with verifiers, subagent orchestration — capability up, cost up superlinearly); and <b>on-device models</b> (1–4B models on NPUs for privacy/latency, hybrid local+cloud routing). The durable skill is separating <em>durable principles</em> (economics, evals, security, context budgeting) from <em>churn</em> (rankings, specific APIs, counts), and date-stamping volatile claims because they will be wrong within a year.</p>' },
    { name: '⚙️ Internals', html: '<p>Reasoning models are RL-trained to emit long chains of intermediate tokens before the answer, rewarded by automatic verifiers (unit tests pass, proof checks) rather than human taste — so they self-correct within the thinking budget, which is why they crack problems prompted CoT can\'t. The cost is real: thinking tokens are billed and add seconds of latency, so you gate them to hard queries. Agent swarms trade tokens for reliability via redundancy (N attempts + a verifier picking the best), but cost scales with N and coordination overhead grows. On-device inference leans on aggressive quantization and small-but-overtrained models; the hybrid pattern routes sensitive/simple work local, hard work to the cloud.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Reasoning tiers waste money on easy tasks</b> — route to them, don\'t default to them.</li><li><b>Agent swarms\' cost scales with N</b> — verify the reliability gain beats the multiplied spend.</li><li><b>Every specific claim here is perishable</b> — date-stamp it and re-check against your own eval.</li><li><b>Leaderboard SOTA rarely transfers to your task</b> — benchmark literacy over benchmark worship.</li><li><b>On-device capability is real but bounded</b> — know the 1–4B ceiling before promising offline magic.</li><li><b>Chasing weather burns time</b> — invest in the climate skills that compound.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m22', moduleId: 'm22-interview-career', title: 'Interview & career in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Interviewing for AI engineering is <b>auditioning as the person who ships the whole restaurant, not the one who reviews ovens</b>. The panel isn\'t testing whether you memorized model specs (weather — see module 21); they\'re testing whether you can take a vague ask ("build us a support bot") and drive it to a system with data, guardrails, evals, and a cost model — out loud, under pressure. Your portfolio is your tasting menu: not "I called an API," but "I built it, evaluated it on a golden set, measured its cost, and here\'s exactly where it breaks." As a 10-year SWE you already have the systems muscle; you\'re bolting AI-specific judgment onto it.</p>' },
    { name: '🔬 Technical', html: '<p>Role archetypes: <b>product AI engineer</b> (features on top of models — the most common), <b>AI infra/platform</b> (serving, evals, pipelines), <b>research engineer</b> (training/fine-tuning). Rounds typically probe: LLM fundamentals (why hallucination, tokens, sampling — module-1/2 material), an <b>AI system-design round</b> (use the module-20 framework: clarify → data → model tier → context → failure modes → evals → cost), and a practical build (a RAG or agent loop live). The reusable system-design answer framework and a portfolio piece with evals + cost analysis attached are the two highest-leverage prep investments.</p>' },
    { name: '⚙️ Internals', html: '<p>What separates strong answers: on fundamentals, mechanism over vocabulary ("hallucination is the objective working — plausibility ≈ truth only where the corpus was dense" beats "it makes stuff up"); on system design, driving the framework yourself and naming where the design breaks first, plus doing the token-budget arithmetic unprompted; on the build, shipping something that validates and handles a failure case rather than a happy-path demo. Portfolio signal is "deployed and measured": a repo with a golden set, an eval harness, a cost breakdown, and an honest failure-modes section reads as senior in a way a slick demo never does.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Trivia recall is a trap</b> — they can look up specs; they\'re buying judgment.</li><li><b>Happy-path demos undersell you</b> — show evals, cost, and failure analysis.</li><li><b>Not driving the system-design framework</b> reads as junior — lead it, don\'t wait to be prompted.</li><li><b>Date-stamp fast-moving claims in interviews too</b> — "as of early 2026" signals you know it churns.</li><li><b>Comp/market claims go stale fast</b> — verify current numbers before negotiating.</li><li><b>Staying valuable as the field commoditizes</b> means owning judgment (evals, security, economics), not memorizing this quarter\'s SOTA.</li></ul>' }
  ]
});
