/* Intuition builders — Track 1 (core). One per module, 4 levels each. */

COURSE.registerExplainer({
  id: 'x-m01', moduleId: 'm01-how-llms-work', title: 'The LLM in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Imagine the world\'s most-read librarian with a strange constraint: they may only ever answer by <b>guessing the next word</b>, one word at a time, based on everything said so far — then guessing the next, and the next. They\'ve read so much that this word-by-word guessing reconstructs facts, code, and arguments astonishingly well. But notice what they <em>never</em> do: check a source, know what they\'ll say next, or say "let me think" without saying it out loud. When they don\'t know, the guessing machinery keeps producing confident-sounding words anyway — because producing words is the only thing it does.</p>' },
    { name: '🔬 Technical', html: '<p>An LLM computes <code>P(next_token | context)</code> over a fixed vocabulary and generates by sampling in a loop: sample → append → recompute. The network is a decoder-only transformer: embeddings → N blocks of (multi-head self-attention + MLP) writing into a residual stream → unembedding to logits. Training has three stages: <b>pretraining</b> (next-token prediction on ~10<sup>13</sup> tokens; installs knowledge and capability), <b>SFT</b> (instruction–response pairs; installs format), <b>preference tuning</b> (RLHF/DPO; installs tone, refusals, judgment). Chat is stateless: full history is resent and reprocessed each turn.</p>' },
    { name: '⚙️ Internals', html: '<p>Attention is a soft key-value lookup: each position\'s query dots against all earlier keys, softmax weights their values — O(n²) in context length. Causal masking makes past token representations immutable, enabling the KV cache: prefill processes the prompt in one parallel pass (compute-bound), decode emits one token at a time reading the whole cache from HBM (bandwidth-bound) — hence input tokens billed ~3–5× cheaper than output. Per-token serial compute is fixed at N layers, so multi-step reasoning must externalize intermediate state into emitted tokens: chain-of-thought is working memory, not theater. MLPs (~⅔ of params) store most factual associations; attention heads route and copy (induction heads power in-context learning).</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Hallucination is the objective, not a bug:</b> plausibility ≈ truth only where the corpus was dense; lossy weights interpolate the rest, and sampling never abstains by default.</li><li><b>No privileged self-access:</b> "why did you say X" returns a sampled story, not a trace. Never build on self-reports.</li><li><b>All tokens are equal citizens:</b> instructions and data share one stream — prompt injection is architectural.</li><li><b>Attribution matters for fixes:</b> missing knowledge → retrieval/tools (not fine-tuning); wrong format → SFT/prompting; wrong attitude → you can\'t fully fix trained refusals from outside.</li><li><b>Scaling laws predict loss, not your task:</b> never extrapolate your eval across model generations — measure.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m02', moduleId: 'm02-tokens-sampling', title: 'Tokens & sampling in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The model reads and writes in <b>Lego bricks, not letters</b>. Common words are single bricks; rare words get snapped together from fragments. Ask it to count the letters in a brick and it\'s guessing — it never saw letters, just the brick. Sampling is the answer-picking hand: <b>temperature</b> is how caffeinated the hand is (steady = always the top choice; jittery = grabs long shots), and <b>top-p</b> is a bouncer that first ejects the absurd options so the jittery hand can\'t reach them.</p>' },
    { name: '🔬 Technical', html: '<p>BPE builds a vocabulary (~100–200k) by iteratively merging frequent byte pairs; text becomes token IDs (≈4 chars/token in English, 2–5× worse for many non-Latin scripts — pricing, context, and rate limits are all denominated in these units). Each step the model emits logits; <b>temperature</b> divides them pre-softmax (sharpen/flatten), <b>top-k/top-p/min-p</b> truncate the candidate set, then one token is sampled. T→0 = argmax. Logprobs expose per-token probabilities — a usable (relative, uncalibrated) confidence signal.</p>' },
    { name: '⚙️ Internals', html: '<p>Merges are frequency statistics frozen at tokenizer training: " the"≠"the", digits chunk in ≤3-digit groups (breaking carry alignment), rare identifiers shatter. Sampler order matters (temperature-then-top-p vs reverse differ; llama.cpp lets you reorder). Temperature-0 nondeterminism has a serving-side mechanism: fp16 reductions aren\'t associative and kernel reduction order depends on continuous-batch composition — near-tied logits flip, one flip cascades. Add MoE routing under load, heterogeneous fleets, and silent snapshot changes; seeds are best-effort.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Character-blind:</b> letter counting, exact lengths, string reversal — enforce in code, not prompts.</li><li><b>Unpinned temperature is an unpinned dependency:</b> default T≈1 on an extraction endpoint = rare tail samples breaking JSON at 0.5% rates.</li><li><b>T=0 ≠ reproducible:</b> test properties and distributions, never exact strings.</li><li><b>RLHF wrecks calibration:</b> logprob 0.98 on wrong answers happens; calibrate thresholds on your data and monitor drift.</li><li><b>Tokens aren\'t portable:</b> vendor migration estimates must re-tokenize real traffic (10–30% count swings).</li><li><b>Loops compound:</b> a 4k-token tool output in a 10-step agent ≈ 40k extra input tokens per episode.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m03', moduleId: 'm03-prompt-engineering', title: 'Prompt engineering in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>A prompt is the <b>briefing you give a brilliant, literal-minded contractor who forgets everything the moment the job ends</b>. Vague brief, uneven results. The <b>system prompt</b> is the standing contract stapled to the front — role, boundaries, house style, what "done" looks like. <b>Few-shot examples</b> are three finished jobs on the desk: the contractor pattern-matches the format faster than any adjective could describe it. Asking for the reasoning out loud (<b>chain-of-thought</b>) is telling them to show their working on the whiteboard instead of blurting a number. And because they forget everything each time, you don\'t "train" them — you rewrite the briefing and re-run.</p>' },
    { name: '🔬 Technical', html: '<p>Prompting is context construction under a token budget. The <b>system prompt</b> sets role, constraints, and output contract; it is not privileged tokens, just conventionally-honored ones placed first. <b>Few-shot</b> (in-context learning) supplies k input→output exemplars; 2–5 usually captures most of the gain, and example <em>distribution</em> matters more than count. <b>Chain-of-thought</b> ("think step by step" or a structured scratchpad) trades output tokens for accuracy on multi-step tasks by externalizing intermediate state. <b>Prompt caching</b> lets you mark a long stable prefix (system + examples + docs) so the provider reuses its KV cache — as of early 2026 cached input reads run roughly 10% of the uncached input price. Treat prompts as <b>versioned artifacts</b>: pin them, diff them, eval every change.</p>' },
    { name: '⚙️ Internals', html: '<p>There is no separate "instruction channel": the chat template concatenates system/user/assistant turns into one token stream with role delimiters the model learned to respect during post-training — respected statistically, not enforced. Few-shot works because induction heads copy and complete patterns already present in context, which is why format consistency across your examples matters more than prose. CoT helps because per-token serial compute is fixed at N layers; emitting reasoning tokens gives the model more forward passes to condition on. Prompt caching keys on an <em>exact token-prefix match</em> — the cache is the precomputed KV tensors for that prefix, so a single changed byte near the top (a timestamp, a reordered field) invalidates everything downstream and you pay full price. This is why stable content goes first, volatile content last.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Caching is prefix-exact:</b> putting a per-request timestamp or user name at the top of a cached block silently busts the cache and multiplies cost 10×.</li><li><b>CoT can lower accuracy on trivial tasks</b> and its stated reasoning is not a faithful trace — it can confabulate a rationale for an answer it reached otherwise.</li><li><b>Few-shot examples leak:</b> the model over-copies their surface form (entity names, lengths, an accidental bias) — audit examples as carefully as instructions.</li><li><b>"Polite" verbosity taxes you</b> — every clarifying sentence in a cached system prompt is cheap, but every unpinned example you keep tweaking re-bills full input.</li><li><b>Prompts are load-bearing code with no type system:</b> ship them through PRs and evals, not a prod textbox; a one-word edit can move a metric 15 points.</li><li><b>System-prompt obedience degrades over long contexts</b> and under adversarial user input — never rely on it as a security boundary.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m04', moduleId: 'm04-model-apis', title: 'Model APIs in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Calling a model API is like <b>ordering from a world-class kitchen through a hatch</b>. You don\'t get the chef; you hand in a ticket (the full conversation, every time — the kitchen keeps no memory of your table) and get a plate back. <b>Streaming</b> is the plate coming out one bite at a time so you can start eating while it cooks. <b>Rate limits</b> are the kitchen refusing tickets when the pass is jammed — push harder and they throw your ticket on the floor (a 429), so you wait and re-submit, backing off longer each time. And the bill isn\'t per plate — it\'s <b>weighed by the word</b>, both what you sent in and what came back out, with the outbound words costing several times more.</p>' },
    { name: '🔬 Technical', html: '<p>The lingua franca is a <b>chat-completions</b> shape: a list of <code>{role, content}</code> messages (system/user/assistant, plus tool roles) sent stateless on every call. Responses stream as <b>server-sent events</b> delivering token deltas, ending in a <code>finish_reason</code> (stop, length, tool_calls, content_filter). Throughput is governed by two ceilings — <b>RPM</b> (requests/min) and <b>TPM</b> (tokens/min); exceed either and you get HTTP 429 with a <code>Retry-After</code>. Correct client behavior is exponential backoff with jitter, honoring that header. Cost is <code>input_tokens × in_price + output_tokens × out_price</code>; as of early 2026 flagship models run roughly $2–5 per million input tokens and $10–20 per million output, mid-tier models ~10× cheaper, with a cached-input tier cheaper still. Providers differ in tool-calling, JSON modes, and context length, but the message contract is largely portable.</p>' },
    { name: '⚙️ Internals', html: '<p>Under the hatch, your request joins a <b>continuous batch</b>: the server interleaves your decode steps with other users\' on the same GPUs, which is why identical inputs can yield different latencies and why strict determinism is unavailable. Prefill (processing your whole prompt) is one parallel compute-bound pass; decode is token-by-token and bandwidth-bound, so <b>time-to-first-token</b> scales with prompt length while <b>inter-token latency</b> is roughly fixed per model. Streaming exists because that TTFT-then-steady-drip profile maps perfectly to SSE. Rate limits are token-bucket accounting per key/org; 429s are backpressure, not errors — a well-behaved client\'s effective throughput is set by how gracefully it backs off. Gateways in front (load balancers, safety classifiers, prompt-cache lookup) add a few hundred ms and occasionally a 5xx you must retry idempotently.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Retries without jitter cause thundering herds:</b> every client backing off to the same instant re-jams the kitchen — always add randomized jitter.</li><li><b>A dropped SSE stream can still bill you</b> for tokens generated before the disconnect; budget for partial-response cost.</li><li><b>TPM, not RPM, is usually your real ceiling</b> — one 100k-token request can consume a minute\'s budget that would have served hundreds of small calls.</li><li><b>finish_reason=length is silent truncation:</b> your JSON just ends mid-string; always check it, never assume completion.</li><li><b>Provider "compatible" endpoints leak differences</b> — tool-call formatting, system-prompt handling, and token counting diverge; re-eval on every migration.</li><li><b>Streaming complicates safety and structure:</b> you can\'t validate a schema or run an output filter until the stream completes, so partial UI must be revocable.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m05', moduleId: 'm05-structured-outputs', title: 'Structured outputs in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Left alone, the model fills in a <b>blank sheet of paper</b> — beautiful prose, but your parser wanted a form. <b>Structured outputs</b> hand it a <b>form with rigid boxes</b>: this box takes a number, that one a date, these three are required. <b>Constrained decoding</b> is a clipboard that physically won\'t let the pen stray outside the boxes — at every stroke it greys out any character that would break the form. <b>Tool calling</b> is the same form, but submitting it dispatches a real errand (query the DB, hit the weather API); the errand\'s result comes back on a fresh line and the model reads it and continues. And a <b>validation loop</b> is the clerk who checks the submitted form, and if a box is wrong, hands it back saying "field 3 must be a positive integer — redo just that."</p>' },
    { name: '🔬 Technical', html: '<p>Two mechanisms, often conflated. <b>Schema-constrained decoding</b> (aka JSON mode / structured outputs) compiles a JSON Schema into a grammar and masks the token logits at each step so only schema-valid continuations are sampleable — the output is guaranteed to parse and match structure. <b>Tool/function calling</b> exposes named tools with JSON-schema parameters; the model emits a structured call, your code executes it, and you append a <code>tool</code>-role message with the result for the next turn — a request→call→execute→observe round trip, often looped. Guarantees are about <em>shape, not truth</em>: constrained decoding can\'t make a field\'s value correct, only well-typed. Robust systems wrap both in a <b>validate-and-repair loop</b>: parse, run business-rule validation (Pydantic/zod), and on failure re-prompt with the specific error, capped at a couple retries.</p>' },
    { name: '⚙️ Internals', html: '<p>Constrained decoding maintains a grammar/automaton alongside generation; at each step it computes the set of tokens that keep a valid prefix and sets all other logits to −∞ before sampling. Because vocab is ~100–200k tokens and the valid set is recomputed per step, providers precompile the schema to a state machine and cache token-mask lookups — complex schemas (deep nesting, regex patterns, large enums) raise per-token cost and can slow decode. Tool calling is not a special channel: the model was post-trained to emit a specific delimited format the API parses back into a call object; under the hood it is still next-token prediction shaped by fine-tuning. The round trip is stateless like everything else — the tool result must be re-sent in full each turn, so verbose tool outputs inflate every subsequent call in the loop.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Valid JSON ≠ correct JSON:</b> constrained decoding guarantees a well-typed <code>{"refund": 999999}</code> just as happily as the right number — you still need semantic validation.</li><li><b>Over-constraining degrades reasoning:</b> forcing structure too early (no room for a scratchpad field) can lower answer quality; give the model a place to think, then a place to answer.</li><li><b>Schema complexity has a latency tax</b> — deep nesting, long enums, and regex constraints slow per-token decode and can hit internal limits.</li><li><b>The model can hallucinate tool arguments</b> — plausible IDs, made-up enum values not in your schema (if unconstrained), or calling a tool it shouldn\'t; validate args before executing side effects.</li><li><b>Repair loops can diverge:</b> re-prompting with an error sometimes yields a new different error; cap retries and fall back, or you get an infinite bill.</li><li><b>Providers implement JSON mode differently</b> — some guarantee validity, some only bias toward it; know which you have before trusting the parse.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m06', moduleId: 'm06-embeddings-vector-search', title: 'Embeddings & search in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Imagine every sentence gets pinned to a spot on an enormous <b>map of meaning</b>, where "how do I reset my password" and "I forgot my login" land practically on top of each other even though they share no words. An <b>embedding</b> is that map coordinate. Search becomes "find the pins nearest my question." But the map has thousands of dimensions and billions of pins, so you can\'t measure every distance — <b>HNSW</b> is a set of highways: express lanes that hop you to the right neighborhood in a few jumps, then local roads to the exact block. It\'s fast because it <em>doesn\'t</em> check everything, which is also why it occasionally drives past the truly closest pin.</p>' },
    { name: '🔬 Technical', html: '<p>An embedding model maps text to a dense vector (~384–3072 dims as of early 2026) where semantic similarity ≈ geometric proximity. Similarity is usually <b>cosine</b> (angle) or dot product; on normalized vectors cosine and Euclidean rank identically. Exact nearest-neighbor over millions of vectors is too slow, so we use <b>approximate NN</b> — <b>HNSW</b> (a navigable small-world graph with hierarchical layers) gives sub-millisecond queries at high recall, tuned by <code>M</code> (graph degree) and <code>efSearch</code> (candidate breadth). Text must first be <b>chunked</b>: too big dilutes the embedding, too small loses context — 200–500 tokens with overlap is a common start. Best retrieval as of early 2026 is <b>hybrid</b>: fuse dense (semantic) with sparse lexical (BM25) via reciprocal-rank fusion, over-retrieve ~20–50 candidates, then <b>rerank</b> with a cross-encoder that scores each query–doc pair jointly for precision.</p>' },
    { name: '⚙️ Internals', html: '<p>Bi-encoder embedding models encode query and document <em>independently</em> into one vector each — cheap and cacheable, but the two never "see" each other, so fine-grained relevance is lost; that\'s exactly what a <b>cross-encoder reranker</b> recovers by concatenating query+doc through a transformer to output a single relevance score (accurate but O(candidates) forward passes, so only on a shortlist). HNSW builds layered proximity graphs; search greedily descends from a sparse top layer to the dense base, keeping <code>efSearch</code> best candidates — higher ef trades latency for recall, and the index is memory-resident (a million 1024-dim float32 vectors ≈ 4GB before graph overhead). Cosine works because training pulls paraphrases together and pushes negatives apart via contrastive loss, carving a space where direction encodes meaning and magnitude is largely normalized away.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Embedding spaces are model-specific:</b> you cannot compare vectors from two different models, and re-embedding the whole corpus is mandatory on any model upgrade.</li><li><b>ANN silently trades recall for speed:</b> a low <code>efSearch</code> can miss the actual best doc; measure recall@k against exact search on a sample.</li><li><b>Pure semantic search fumbles exact tokens</b> — error codes, SKUs, names, negation ("not refundable") — which is why lexical hybrid is not optional for real corpora.</li><li><b>Chunking is where most RAG quality is won or lost:</b> splitting mid-table or mid-sentence poisons the embedding; respect document structure.</li><li><b>Cosine similarity has no absolute meaning</b> — 0.82 isn\'t "82% relevant"; thresholds must be calibrated per model and domain, and drift over time.</li><li><b>Vector count drives cost more than you expect:</b> RAM-resident indexes get expensive fast; dimensionality-reduction (Matryoshka/MRL) and quantization are how you keep a large index affordable.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m07', moduleId: 'm07-rag', title: 'RAG in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>RAG is an <b>open-book exam</b> for a student with a phenomenal writing style but a shaky, out-of-date memory. Instead of trusting recall, you let them <b>look up the relevant pages first</b>, then write the answer citing what they found. The magic and the danger both live in the lookup: hand them the right three pages and the essay is excellent and grounded; hand them the wrong pages (or pages that <em>look</em> related but aren\'t) and they\'ll write an equally confident, equally fluent essay built on the wrong facts — and they\'ll never tell you the pages were wrong, because from the inside, retrieved text and remembered text feel identical.</p>' },
    { name: '🔬 Technical', html: '<p>The pipeline has two halves. <b>Ingest (offline):</b> load → chunk → embed → index into a vector store (plus a lexical index for hybrid). <b>Query (online):</b> embed the question → retrieve top-k (ideally hybrid + rerank) → assemble a prompt with the retrieved passages and citations → generate a grounded answer. RAG is the right tool when knowledge is <b>private, large, or changing</b> — you update the index, not the weights. Evaluation must cover both stages separately: <b>retrieval</b> (recall@k, MRR, nDCG — did the right chunk come back at all?) and <b>generation</b> (faithfulness/groundedness — is the answer supported by the retrieved context, and answer relevance). The dominant failure isn\'t bad writing; it\'s the generator confidently answering from context that never contained the answer.</p>' },
    { name: '⚙️ Internals', html: '<p>At generation time the retrieved chunks are simply concatenated into the prompt — they are ordinary tokens with no special "this is ground truth" status, which is why the model can still ignore them, blend them with parametric memory, or hallucinate around gaps. That also means <b>context ordering matters</b> (lost-in-the-middle: mid-context passages get underweighted) and <b>token budget is real</b> — stuffing 20 chunks can bury the useful one and inflate cost/latency. Faithfulness is improved by instructing the model to answer <em>only</em> from context and to say "not in the provided documents" when unsupported, plus post-hoc citation checking (does each claim map to a retrieved span?). Retrieval quality dominates end-to-end quality: a perfect generator over the wrong three chunks is worthless, so most RAG debugging is retrieval debugging.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Retrieval failure masquerades as hallucination:</b> the model answers fluently from wrong or empty context — instrument what got retrieved before blaming the generator.</li><li><b>RAG can\'t answer aggregate or global questions</b> ("summarize all 500 tickets", "what\'s the trend") — top-k retrieval sees fragments, not the whole; that needs different architectures.</li><li><b>Stale or duplicated chunks poison answers</b> — index freshness and dedup are ongoing ops work, not a one-time load.</li><li><b>When to NOT use RAG:</b> if the knowledge fits in the context window, is fully public and in-weights, or the task needs reasoning over the entire corpus, RAG adds latency and failure surface for no gain.</li><li><b>Retrieved context is an injection vector:</b> a malicious document in your corpus can carry instructions the model obeys — treat retrieved text as untrusted data.</li><li><b>"Add more chunks" usually hurts</b> — it raises cost, latency, and lost-in-the-middle risk; better retrieval beats more retrieval.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m08', moduleId: 'm08-context-engineering', title: 'Context engineering in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The context window is a <b>cluttered desk, not a filing cabinet</b>. Everything the model can use right now must be on the desk — but a bigger desk doesn\'t mean better work. Pile on 200 documents and the model, like a tired reader, <b>skims the top and bottom of the stack and glazes over the middle</b>. Context engineering is being the ruthless desk manager: put the one memo that matters where the eyes actually land, sweep finished paperwork into a labeled folder (a running summary), and refuse to let old scratch notes crowd out the live task. The skill isn\'t filling the desk — it\'s deciding what earns a spot on it this turn.</p>' },
    { name: '🔬 Technical', html: '<p>Context engineering is deciding <b>what tokens occupy the window and in what order</b>, under a fixed budget, to maximize task performance. Core phenomena: <b>lost-in-the-middle</b> — retrieval/attention accuracy is U-shaped, strong at the start and end of context, weak in the middle — so critical instructions and key evidence go at the edges. <b>Budgeting</b>: allocate the window across system prompt, task, retrieved docs, tool outputs, and history; more tokens cost more, raise latency, and dilute attention. <b>Compaction</b>: as a conversation or agent loop grows, summarize or prune old turns (rolling summaries, drop stale tool outputs) rather than resending everything. <b>Memory</b>: persist salient facts outside the window (a store or scratchpad) and re-inject only what\'s relevant this turn, since the model itself is stateless between calls.</p>' },
    { name: '⚙️ Internals', html: '<p>Lost-in-the-middle is a real property of attention and positional encoding, not a prompt-wording issue — long-context training under-optimizes middle positions, so a "1M token" window does not mean uniform recall across it; effective usable context is smaller than advertised. Every token also costs O(n²)-ish attention compute and linear KV-cache memory, so a bloated window degrades both latency and, past a point, quality. Compaction works because the model is stateless: nothing forces you to resend raw history — a faithful 300-token summary of 8k tokens of prior turns preserves the decision-relevant state at a fraction of cost, though it risks dropping a detail that later turns out to matter. Memory systems are just retrieval (from §m06) pointed at conversation state, which is why they inherit the same wrong-chunk failure modes.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>A bigger window is not a free upgrade:</b> filling it usually lowers accuracy and always raises cost/latency — measure quality vs. tokens, don\'t assume monotonic gains.</li><li><b>Advertised context ≠ usable context:</b> mid-context recall degrades sharply; validate on <em>your</em> long-context task, never trust the spec number.</li><li><b>Compaction is lossy by definition</b> — the summary that drops "the customer is on the enterprise plan" quietly breaks turn 12; decide what must survive.</li><li><b>Agent loops silently accrete context:</b> every tool result appended each turn compounds — a 4k output over 10 steps is 40k+ recurring tokens; prune aggressively.</li><li><b>Order is a lever, not a formality:</b> the same tokens at the middle vs. the end can swing whether the model uses them.</li><li><b>Memory retrieval can inject stale or contradictory facts</b> — a remembered preference from three tasks ago may now be wrong; scope and expire memories.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m09', moduleId: 'm09-agents-loop', title: 'The agent loop in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>A plain LLM call is <b>asking an expert a question and getting one answer</b>. An agent is handing that same expert a <b>to-do note, a phone, and permission to keep working until it\'s done</b>: they look at the situation, decide a next action, make a call (run a tool), read what came back, and loop — reassessing each time — until the task is finished or they hit a wall. The power is that they can course-correct mid-task. The peril is the same: with no one saying "stop," a confused agent will keep confidently making calls, spending money and touching real systems, long after it should have asked for help.</p>' },
    { name: '🔬 Technical', html: '<p>An agent is an LLM run in a loop: <b>perceive</b> (current state + goal in context) → <b>plan/decide</b> (what to do next) → <b>act</b> (call a tool) → <b>observe</b> (append the result) → repeat. <b>ReAct</b> is the canonical pattern: interleave explicit reasoning traces with actions, so the model conditions each tool call on a written rationale and each result on prior reasoning. The loop needs hard <b>stop conditions</b>: goal satisfied, max iterations, budget/time cap, repeated-action detection, or an explicit "ask the human." Without them you get runaway loops. Crucially, agency is a cost/latency/reliability multiplier — a 10-step episode is 10+ model calls with accreting context — so the senior instinct is: <b>reach for the simplest thing that works</b>. A single well-prompted call or a fixed pipeline beats an agent whenever the task is deterministic.</p>' },
    { name: '⚙️ Internals', html: '<p>Mechanically the loop is just repeated stateless chat calls where each turn\'s input is the whole history plus the latest tool result; the "agent" is orchestration code around the model, not a new capability in it. Reliability compounds multiplicatively: if each step is 95% reliable, a 10-step chain is ~60% — which is why long agent runs fail so much more than single calls and why bounding step count matters. Context grows every iteration (tool outputs appended), so long episodes hit lost-in-the-middle and cost blowups unless you compact. ReAct helps because the emitted reasoning tokens give the model more forward passes and a legible trace, but that trace is a generated artifact, not a guaranteed-faithful log of why it acted. Stop conditions live entirely in your harness — the model won\'t reliably stop itself.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Reliability compounds against you:</b> 95% per step over 10 steps ≈ 60% end-to-end — long autonomous chains are inherently fragile; shorten them.</li><li><b>Loops without a budget are a runaway bill</b> and a runaway blast radius — always cap iterations, cost, and wall-clock, and detect repeated actions.</li><li><b>When NOT to build an agent:</b> if the steps are known and fixed, a deterministic pipeline is cheaper, faster, debuggable, and far more reliable than an LLM deciding each hop.</li><li><b>Agents amplify prompt injection:</b> a poisoned tool result or web page becomes an instruction the agent acts on with real permissions.</li><li><b>The reasoning trace is not an audit log</b> — don\'t trust "I did X because Y" as proof of what actually happened; instrument the actual tool calls.</li><li><b>Error recovery is the hard 20%:</b> demos handle the happy path; production is tool timeouts, malformed results, and the agent doubling down on a wrong plan.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m10', moduleId: 'm10-agentic-systems', title: 'Agentic systems in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>One agent is a capable freelancer. An <b>agentic system</b> is a whole <b>contractor crew with subcontractors, standardized power outlets, and a locked job site</b>. A lead agent parcels work to specialists (<b>multi-agent</b>). Every tool and data source plugs into the same standardized socket so any agent can use any tool (<b>MCP</b> is that socket standard). Some workers get to actually drive the on-site computer — click, type, screenshot (<b>computer use</b>) — which is powerful and exactly why you fence the site: they work inside a locked, disposable trailer (<b>sandbox</b>) and a human signs off before anything leaves the site or spends real money (<b>human-in-the-loop</b>). The more autonomy and reach you grant, the more the fencing becomes the actual engineering.</p>' },
    { name: '🔬 Technical', html: '<p>Beyond a single loop you compose. <b>Multi-agent</b> patterns (orchestrator–worker, planner–executor, debate) split a task across specialized agents with distinct prompts/tools — sometimes better via separation of concerns, often just more cost and coordination failure, so justify it. <b>MCP (Model Context Protocol)</b> is an open standard (introduced late 2024, widely adopted through 2025) for exposing tools, resources, and prompts to models over a uniform interface, so integrations become plug-in servers instead of bespoke glue. <b>Computer use</b> gives a model screenshots + keyboard/mouse actions to operate real GUIs — broad reach, but slow, brittle, and high-stakes. Non-negotiable controls: <b>sandboxing</b> (isolated, least-privilege, disposable execution environments), and <b>human-in-the-loop</b> approval gates on irreversible or high-value actions.</p>' },
    { name: '⚙️ Internals', html: '<p>Each agent in a multi-agent system is still its own stateless LLM loop; "communication" is just one agent\'s output becoming another\'s input tokens, so errors and hallucinations propagate across the mesh and context has to be re-passed at every hop — coordination overhead is real tokens and real latency. MCP standardizes the tool-schema and transport layer (JSON-RPC-style), so from the model\'s side an MCP tool is an ordinary function-calling schema; the value is operational (reuse, discovery), not a new model capability — and every connected server widens the attack surface. Computer use is a perception+action loop over pixels: the model reads a screenshot, emits a click coordinate or keystrokes, observes the next screenshot — inheriting all agent-loop fragility plus GUI flakiness. Sandboxing and HITL are enforced in your infrastructure, never by the model\'s good intentions.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Multi-agent is usually premature:</b> it multiplies cost, latency, and failure modes — reach for it only when a single agent with good tools genuinely can\'t, and prove the win.</li><li><b>Every MCP server is trust delegated:</b> a compromised or malicious server can exfiltrate context or inject instructions — vet and scope them like third-party dependencies.</li><li><b>Connecting private data + a tool that can act + exposure to untrusted content = the lethal trifecta</b>; agentic systems assemble it by default.</li><li><b>Computer use is slow and brittle</b> — minor UI changes break it, and it operates with whatever the logged-in session can do; sandbox it hard.</li><li><b>Sandboxes leak via their tools:</b> an isolated runtime with an unrestricted network egress or a broad API key isn\'t isolated — least privilege on <em>every</em> capability.</li><li><b>HITL fatigues into rubber-stamping:</b> too many low-signal approval prompts and humans click "yes" reflexively — gate only the truly irreversible, and make the ask legible.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m11', moduleId: 'm11-evals', title: 'Evals in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Shipping an LLM feature without evals is <b>refactoring with no test suite</b> — every change feels fine until it silently breaks something you weren\'t looking at. An eval is that test suite for a system whose outputs aren\'t exact strings. A <b>golden set</b> is your regression tests: fixed inputs with known-good outputs you re-run on every change. Because "correct" is fuzzy, you sometimes appoint the model itself as the grader (<b>LLM-as-judge</b>) — useful, but like a slightly star-struck examiner: it rewards longer, more confident, better-formatted answers, and quietly favors work that sounds like its own. So you keep a <b>human-graded anchor set</b> to audit the examiner, and you never let a metric move without a gate catching it.</p>' },
    { name: '🔬 Technical', html: '<p>Evals span a spectrum. <b>Deterministic checks</b> (exact match, regex, schema-valid, code passes tests) — cheap, reliable, use wherever the task allows. <b>LLM-as-judge</b> — a model scores outputs against a rubric or picks a winner (pairwise); scalable for open-ended quality but biased. <b>Human eval</b> — the ground-truth anchor, expensive, reserved for calibration and hard cases. A <b>golden/eval set</b> is a curated, versioned collection of representative and adversarial cases with expected outcomes; you run it in CI as a <b>regression gate</b> that blocks a prompt/model change if a metric regresses. Known judge biases (as of early 2026): <b>position bias</b> (favors first option), <b>verbosity bias</b> (longer = better), <b>self-preference</b> (favors its own family\'s style), and sensitivity to formatting. Mitigate by randomizing order, forcing rubric-anchored scoring, and validating the judge against human labels.</p>' },
    { name: '⚙️ Internals', html: '<p>LLM-as-judge is just another sampled generation, so it inherits every LLM property: it\'s stochastic (same output can get different scores across runs), miscalibrated (confident wrong grades), and steerable by surface features — which is precisely why its scores must themselves be validated against human labels before you trust them as a gate. Pairwise comparison is more reliable than absolute 1–10 scoring because relative judgments are easier and less scale-arbitrary, but position bias means you must run both orderings and average. Golden sets rot: as the product and model change, yesterday\'s cases stop representing today\'s traffic, so they need continuous refresh from production logs. A regression gate works statistically — small metric moves can be noise, so you need enough cases and ideally significance thresholds, not a single-example tripwire.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>An unvalidated LLM judge is a vibe with a number on it:</b> always spot-check its grades against human labels before gating on them.</li><li><b>Judge biases are systematic, not random:</b> verbosity, position, and self-preference will inflate exactly the outputs you shouldn\'t reward — control for them explicitly.</li><li><b>Benchmark scores are marketing without context:</b> contamination (test data in training), non-representative distributions, and cherry-picked configs mean a leaderboard number rarely predicts your task — always build a task-specific eval.</li><li><b>Golden sets go stale silently</b> — a suite that no longer resembles production passes while real quality drops; refresh from live traffic.</li><li><b>Teaching to the test:</b> optimizing prompts against a small fixed eval overfits it; hold out cases and rotate them.</li><li><b>A single flaky example is not a regression</b> — evals are statistical; gate on aggregates with enough n, or you\'ll chase noise.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m12', moduleId: 'm12-observability', title: 'Observability in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>A traditional service tells you <em>what</em> broke — a 500, a stack trace. An LLM app usually returns a fluent, 200-OK, completely-wrong answer, so the old dashboards stay green while quality quietly rots. LLM observability is the <b>flight recorder for a system that never technically crashes</b>: it captures every prompt, every retrieved chunk, every tool call, every token count and dollar and millisecond, so when a user says "the answer was garbage" you can replay the exact flight instead of guessing. And because the model and the world change under you, it watches for <b>drift</b> — the slow slide where nothing errors but yesterday\'s good answers stop being good.</p>' },
    { name: '🔬 Technical', html: '<p>The unit of observability is the <b>trace</b>: a tree of <b>spans</b> capturing each step of a request — the LLM call (full prompt, response, model, params), retrieval (query + returned chunks + scores), tool calls (args + results), and nested agent steps. Per span you record the three operational vitals: <b>tokens</b> (in/out, driving cost), <b>cost</b> ($), and <b>latency</b> (TTFT and total). OpenTelemetry-style semantic conventions for GenAI have matured (through 2025) so this is increasingly standardized. On top you layer <b>online quality signals</b>: sampled LLM-as-judge scores, guardrail hits, and <b>user feedback</b> (thumbs, edits, regenerations, abandonment) fed back into eval sets. <b>Drift</b> monitoring watches input distribution, output metrics, and cost/latency over time to catch silent degradation from model snapshot changes, data shift, or prompt edits.</p>' },
    { name: '⚙️ Internals', html: '<p>Tracing an LLM app means capturing the full prompt and response as span attributes, which is why observability and data governance collide: those payloads contain user PII and your prompts, so storage, redaction, and retention are part of the design, not an afterthought. Latency decomposes into queue time, TTFT (grows with prompt length, prefill-bound), and inter-token time (model-fixed) — you can\'t fix p95 latency without knowing which piece dominates. Cost attribution requires per-span token counts because one user request can fan out into many model/tool calls (especially agents), and the expensive one is rarely the one you\'d guess. Drift is detectable only with a baseline: you need historical distributions of inputs, outputs, and quality scores, because "the model got worse" is invisible without something to compare against — and providers can change a snapshot under a stable name.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>200 OK is not success:</b> the request "worked" while returning a confidently wrong answer — HTTP-level monitoring is blind to quality, you must instrument outputs.</li><li><b>You cannot debug what you did not capture:</b> if you logged only the final answer, not the retrieved chunks and tool calls, a bad-answer report is unsolvable — trace the whole chain.</li><li><b>Traces are a PII lake:</b> full prompts/responses often contain sensitive data — redaction and retention policy are mandatory, not optional.</li><li><b>Silent snapshot drift:</b> a provider updating the model behind a stable alias can shift your outputs with zero code change — only baseline monitoring catches it.</li><li><b>Cost hides in fan-out:</b> a single agent request can be 20 model calls; without per-span attribution you\'ll optimize the wrong one.</li><li><b>User feedback is sparse and biased</b> — angry users click thumbs-down more than happy users click thumbs-up; triangulate with sampled judges, don\'t trust raw ratios.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m13', moduleId: 'm13-safety-security', title: 'Safety & security in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The core security problem is that an LLM reads <b>instructions and data in the same ink</b> — it cannot tell your standing orders from a note that a stranger slipped into the paperwork. <b>Direct injection</b> is a user writing "ignore your instructions" straight into the chat. <b>Indirect injection</b> is far nastier: the malicious note is hidden inside a web page, a PDF, or an email the agent dutifully reads to do its job — the attacker never talks to your system, they just leave a landmine where it will walk. It gets lethal when three things meet in one agent: <b>access to private data</b>, the <b>ability to act</b> (send, buy, delete), and <b>exposure to untrusted content</b>. Any two are fine; all three is an exfiltration engine waiting for the right poisoned page.</p>' },
    { name: '🔬 Technical', html: '<p><b>Prompt injection</b> exploits the architectural fact that instructions and data share one token stream (§m01). <b>Direct</b>: adversarial input in the user turn (jailbreaks, instruction override). <b>Indirect</b>: adversarial instructions embedded in content the model ingests — retrieved documents, tool outputs, web pages, images — triggered without the attacker touching your interface. The <b>lethal trifecta</b> (Simon Willison\'s framing): private-data access + external communication/action + untrusted-content exposure; remove any one leg to defang it. Defenses are <b>layered, never absolute</b>: input/output <b>guardrails</b> (classifiers for injection, toxicity, policy), least-privilege tool scoping, human approval on high-stakes actions, output filtering, and <b>PII</b> handling (detection, redaction, minimization, no sensitive data in prompts/logs you don\'t control). There is no known prompt that reliably immunizes a model — treat "just tell it to ignore injections" as security theater.</p>' },
    { name: '⚙️ Internals', html: '<p>Injection is unfixable at the prompt layer because it\'s the same mechanism that makes instruction-following work: the model attends over all tokens and was trained to obey imperative language wherever it appears — it has no architectural notion of "trusted" vs "untrusted" spans. Post-training and delimiters raise the bar statistically (harder to trigger) but never to a guarantee, which is why real defense is <b>architectural containment</b>: assume the model can be turned, and limit what a turned model can reach or do. That means the security boundary lives in your infrastructure — scoped credentials, sandboxed execution, egress controls, approval gates — exactly the controls from §m10, applied under an adversarial assumption. PII protection similarly must be structural: redact before the prompt, minimize what you send, and control the trace store, because once sensitive data is in the context it can be echoed, logged, or exfiltrated.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Prompt injection has no complete fix as of early 2026:</b> defenses reduce probability, never to zero — design assuming the model <em>will</em> occasionally be subverted.</li><li><b>Indirect injection needs no access to you:</b> a poisoned web page or document your agent reads is the attack — RAG corpora and tool outputs are untrusted input.</li><li><b>The lethal trifecta assembles quietly:</b> a helpful "read my email and book the thing" agent has private data + action + untrusted content by default — audit for all three legs.</li><li><b>Guardrail classifiers are bypassable</b> — obfuscation, encoding, and novel phrasings evade them; they\'re a layer, not a wall.</li><li><b>PII leaks through logs and traces:</b> the observability you built (§m12) is itself a sensitive-data exposure if unredacted.</li><li><b>Refusals and safety tuning don\'t equal security:</b> a model politely refusing harmful content will still cheerfully follow an injected instruction to exfiltrate data.</li></ul>' }
  ]
});
