/* Intuition builders — Track 1 (core). One per module, 4 levels each. */

COURSE.registerExplainer({
  id: 'x-m01', moduleId: 'm01-how-llms-work', title: 'The LLM in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>Imagine the world\'s most-read librarian with a strange constraint: they may only ever answer by <b>guessing the next word</b>, one word at a time, based on everything said so far — then guessing the next, and the next. They\'ve read so much that this word-by-word guessing reconstructs facts, code, and arguments astonishingly well. But notice what they <em>never</em> do: check a source, know what they\'ll say next, or say "let me think" without saying it out loud. When they don\'t know, the guessing machinery keeps producing confident-sounding words anyway — because producing words is the only thing it does.</p>' },
    { name: '🔬 Technical', html: '<p>An LLM computes <code>P(next_token | context)</code> over a fixed vocabulary and generates by sampling in a loop: sample → append → recompute. The network is a decoder-only transformer: embeddings → N blocks of (multi-head self-attention + MLP) writing into a residual stream → unembedding to logits. Training has three stages: <b>pretraining</b> (next-token prediction on ~10<sup>13</sup> tokens; installs knowledge and capability), <b>SFT</b> (instruction–response pairs; installs format), <b>preference tuning</b> (RLHF/DPO; installs tone, refusals, judgment). Chat is stateless: full history is resent and reprocessed each turn.</p>' },
    { name: '⚙️ Internals', html: '<p>Attention is a soft key-value lookup: each position\'s query dots against all earlier keys, softmax weights their values — O(n²) in context length. Causal masking makes past token representations immutable, enabling the KV cache: prefill processes the prompt in one parallel pass (compute-bound), decode emits one token at a time reading the whole cache from HBM (bandwidth-bound) — hence input tokens billed ~3–5× cheaper than output. Per-token serial compute is fixed at N layers, so multi-step reasoning must externalize intermediate state into emitted tokens: chain-of-thought is working memory, not theater. MLPs (~⅔ of params) store most factual associations; attention heads route and copy (induction heads power in-context learning).</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Hallucination is the objective, not a bug:</b> plausibility ≈ truth only where the corpus was dense; lossy weights interpolate the rest, and sampling never abstains by default.</li><li><b>No privileged self-access:</b> "why did you say X" returns a sampled story, not a trace. Never build on self-reports.</li><li><b>All tokens are equal citizens:</b> instructions and data share one stream — prompt injection is architectural.</li><li><b>Attribution matters for fixes:</b> missing knowledge → retrieval/tools (not fine-tuning); wrong format → SFT/prompting; wrong attitude → you can\'t fully fix trained refusals from outside.</li><li><b>Scaling laws predict loss, not your task:</b> never extrapolate your eval across model generations — measure.</li></ul>' }
  ]
});

COURSE.registerExplainer({
  id: 'x-m02', moduleId: 'm02-tokens-sampling', title: 'Tokens & sampling in four passes',
  levels: [
    { name: '🏠 Analogy', html: '<p>The model reads and writes in <b>Lego bricks, not letters</b>. Common words are single bricks; rare words get snapped together from fragments. Ask it to count the letters in a brick and it\'s guessing — it never saw letters, just the brick. Sampling is the answer-picking hand: <b>temperature</b> is how caffeinated the hand is (steady = always the top choice; jittery = grabs long shots), and <b>top-p</b> is a bouncer that first ejects the absurd options so the jittery hand can\'t reach them.</p>' },
    { name: '🔬 Technical', html: '<p>BPE builds a vocabulary (~100–200k) by iteratively merging frequent byte pairs; text becomes token IDs (≈4 chars/token in English, 2–5× worse for many non-Latin scripts — pricing, context, and rate limits are all denominated in these units). Each step the model emits logits; <b>temperature</b> divides them pre-softmax (sharpen/flatten), <b>top-k/top-p/min-p</b> truncate the candidate set, then one token is sampled. T→0 = argmax. Logprobs expose per-token probabilities — a usable (relative, uncalibrated) confidence signal.</p>' },
    { name: '⚙️ Internals', html: '<p>Merges are frequency statistics frozen at tokenizer training: " the"≠"the", digits chunk in ≤3-digit groups (breaking carry alignment), rare identifiers shatter. Sampler order matters (temperature-then-top-p vs reverse differ; llama.cpp lets you reorder). Temperature-0 nondeterminism has a serving-side mechanism: fp16 reductions aren\'t associative and kernel reduction order depends on continuous-batch composition — near-tied logits flip, one flip cascades. Add MoE routing under load, heterogeneous fleets, and silent snapshot changes; seeds are best-effort.</p>' },
    { name: '🔪 Sharp edges', html: '<ul><li><b>Character-blind:</b> letter counting, exact lengths, string reversal — enforce in code, not prompts.</li><li><b>Unpinned temperature is an unpinned dependency:</b> default T≈1 on an extraction endpoint = rare tail samples breaking JSON at 0.5% rates.</li><li><b>T=0 ≠ reproducible:</b> test properties and distributions, never exact strings.</li><li><b>RLHF wrecks calibration:</b> logprob 0.98 on wrong answers happens; calibrate thresholds on your data and monitor drift.</li><li><b>Tokens aren\'t portable:</b> vendor migration estimates must re-tokenize real traffic (10–30% count swings).</li><li><b>Loops compound:</b> a 4k-token tool output in a 10-step agent ≈ 40k extra input tokens per episode.</li></ul>' }
  ]
});
